cleanup sample-3-1
java-park-mail-ru/samples pull request #7
Opened 2018-04-12 17:10 UTC by isopov

2018-04-18 20:34 UTC, KSolovyev requested changes

2018-04-18 20:34 UTC, KSolovyev commented on sample-3-1/src/test/java/ru/mail/park/mechanics/base/SnapSerializationTest.java
> -    public void clientSnapTest() throws IOException {
блин, а зачем модификаторы-то порезали?

2018-04-19 08:03 UTC, isopov commented on sample-3-1/src/test/java/ru/mail/park/mechanics/base/SnapSerializationTest.java
> -    public void clientSnapTest() throws IOException {
Идея ругается на публичные тесты на Junit5 - во всех остальных примерах все тесты package-private

2018-04-26 11:45 UTC, KSolovyev commented on sample-3-1/src/test/java/ru/mail/park/mechanics/base/SnapSerializationTest.java
> -    public void clientSnapTest() throws IOException {
ок

2018-04-26 11:45 UTC, merged